apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canaryjs-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: os-dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: canaryjs
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  syncPolicy:
    automated:
      prune: true