apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.imageSource }}/{{ .Values.imageName }}:{{ .Values.appVersion }}
        ports:
        - containerPort: {{ .Values.spec.source.containerPort }}
        env:
        - name: JUNK
          valueFrom:
            secretKeyRef:
              name: junk-secret
              key: junk-key
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IMAGENAME
          value: {{ .Values.imageName }}
        - name: APPVERSION
          value: "{{ .Values.appVersion }}"
      imagePullSecrets:
      - name: regnexus
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Chart.Name }}
              topologyKey: kubernetes.io/hostname