apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-stable
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.spec.source.containerPort }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    k8s-app: {{ .Values.appName }}